"""Add user_id column as nullable to survey table

Revision ID: 27f77abad8e5
Revises:
Create Date: 2025-06-16 22:15:58.008582
"""
from alembic import op
import sqlalchemy as sa

revision = '27f77abad8e5'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    with op.batch_alter_table('survey') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

def downgrade():
    with op.batch_alter_table('survey') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('FK__messages__receiv__70DDC3D8')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('FK__messages__sender__6FE99F9F')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__messages__3213E83FD2330A77'))
    )
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('FK__posts__user_id__02FC7413')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__posts__3213E83FF61DD0E1'))
    )
    # ### end Alembic commands ###
